YT_PROJECT/YT_PROJECT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chatapp.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT})
]

YT_PROJECT/chatapp/urls.py
from django.urls import path
from .views import room_views, review_views
from django.contrib.auth import views as auth_views


app_name = 'chatapp'

urlpatterns = [
    path('',room_views.chat_home),
    path('login/', auth_views.LoginView.as_view(template_name='chatapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='chatapp/login.html'), name='logout'),
    path('signup/',room_views.signup, name='signup'),

    path('join/',room_views.join, name='join'),
    path('room_list/',room_views.room_list,name='room_list'),
    path('make_room/',room_views.make_room, name='make_room'),
    path('detail_room/<int:pk>/', room_views.detail_room, name='detail_room'),
    path('delete_room/<int:pk>/', room_views.delete_room, name='delete_room'),
    path('modify_room/<int:pk>/', room_views.modify_room, name='modify_room'),

    path('make_review/<int:pk>/', review_views.make_review, name='make_review'),
    path('delete_review/<int:pk>/<int:id>/', review_views.delete_review, name='delete_review'),

    path('make_re_review/<int:pk>/<int:id>/', review_views.make_re_review, name='make_re_review'),
    path('delete_re_review/<int:pk>/<int:re>/<int:id>/', review_views.delete_re_review, name='delete_re_review')
]

YT_PROJECT/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <title>DISCUSSION CHATTING</title>
</head>
<body>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid justify-content-center">
          <a class="navbar-brand" href="/">
            <img src="{% static 'chatapp/img/logo.png' %}" alt="Logo" width="200" height="35">
          </a>
        </div>
    </nav>
    {% if user.is_authenticated %}
    <div class="row justify-content-end" style="color:gray; font-size:13px;">
      <span style="width:auto; color:black;">{{ user.username }}님이 로그인하였습니다. &nbsp
      <a class="nav-link" href="{% url 'chatapp:logout' %}" style="float:right; color:blue;">로그아웃 &nbsp</a></span> 
    </div>
    {% endif %}
{% block content %}
</body>
</html>
{% endblock %}