YT_PROJECT/YT_PROJECT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chatapp.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT})
]

YT_PROJECT/chatapp/urls.py
from django.urls import path
from .views import room_views, review_views
from django.contrib.auth import views as auth_views


app_name = 'chatapp'

urlpatterns = [
    path('',room_views.chat_home),
    path('login/', auth_views.LoginView.as_view(template_name='chatapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='chatapp/login.html'), name='logout'),
    path('signup/',room_views.signup, name='signup'),

    path('join/',room_views.join, name='join'),
    path('room_list/',room_views.room_list,name='room_list'),
    path('make_room/',room_views.make_room, name='make_room'),
    path('detail_room/<int:pk>/', room_views.detail_room, name='detail_room'),
    path('delete_room/<int:pk>/', room_views.delete_room, name='delete_room'),
    path('modify_room/<int:pk>/', room_views.modify_room, name='modify_room'),

    path('make_review/<int:pk>/', review_views.make_review, name='make_review'),
    path('delete_review/<int:pk>/<int:id>/', review_views.delete_review, name='delete_review'),

    path('make_re_review/<int:pk>/<int:id>/', review_views.make_re_review, name='make_re_review'),
    path('delete_re_review/<int:pk>/<int:re>/<int:id>/', review_views.delete_re_review, name='delete_re_review')
]

YT_PROJECT/chatapp/models.py
from django.db import models
from datetime import datetime
import os
from django.conf import settings
from django.db.models import Max

today = datetime.today().strftime("%Y/%m/%d") 
image_path = "media/"+today+"/"

# Create your models here.
class Room(models.Model):
    #room_name, room_subject, limit_people, limit_date
    room_title = models.CharField(null=False, max_length=30)
    room_content = models.CharField(null=False, max_length=2000)
    room_image1 = models.ImageField(null=True, upload_to=image_path)
    room_image2 = models.ImageField(null=True, upload_to=image_path)
    room_image3 = models.ImageField(null=True, upload_to=image_path)
    room_creater = models.CharField(null=False, max_length=100)
    room_date = models.CharField(null=True, max_length=100)
    room_view = models.IntegerField(null=False, default=0)
    room_like = models.IntegerField(null=False, default=0)

    def delete(self, *args, **kwargs):
        super(Room, self).delete(*args, **kwargs)
        if self.room_image1 != '': 
            os.remove(os.path.join(settings.MEDIA_ROOT, self.room_image1.path))
        if self.room_image2 != '': 
            os.remove(os.path.join(settings.MEDIA_ROOT, self.room_image2.path))
        if self.room_image3 != '': 
            os.remove(os.path.join(settings.MEDIA_ROOT, self.room_image3.path))

    def __str__(self):
        return f"{self.room_title}, {self.room_content}, {self.room_image1}, {self.room_image2}, {self.room_image3}, {self.room_creater}, {self.room_date}, {self.room_view}, {self.room_like} creat!!"

class Review(models.Model):
    review_room =  models.IntegerField(null=False)
    review_content = models.CharField(null=False, max_length=2000)
    review_creater = models.CharField(null=False, max_length=100)
    review_date = models.CharField(null=True, max_length=100)

    def __str__(self):
        return f"{self.review_room}, {self.review_content}, {self.review_creater}, {self.review_date} creat!!"
    
class ReReview(models.Model):
    review_room = models.IntegerField(null=False)
    review_id = models.IntegerField(null=False)
    review_content = models.CharField(null=False, max_length=2000)
    review_creater = models.CharField(null=False, max_length=100)
    review_date = models.CharField(null=True, max_length=100)

    def __str__(self):
        return f"{self.review_room}, {self.review_id}, {self.review_content}, {self.review_creater}, {self.review_date} creat!!"

YT_PROJECT/chatapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="email")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

YT_PROJECT/chatapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from chatapp.forms import UserForm

from django.http import HttpResponse
from chatapp.models import Room, Review

from datetime import datetime

# Create your views here.

# home view (로그인 상태: join.html, 미로그인 상태:login.html)
def chat_home(request):
    if not request.user.is_authenticated:
        return render(request, 'chatapp/login.html',{})
    else:
        return render(request, 'chatapp/join.html', {})

#계정 생성 view
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            authenticate(username=username, password=raw_password)  # 사용자 인증
            # login(request, user)  # 로그인
            return render(request,'chatapp/login.html',context={})
    else:
        form = UserForm()
    return render(request, 'chatapp/signup.html', {'form':form})

#방 참가 view
@login_required
def join(request):
    context = {}
    return render(request, 'chatapp/join.html', context=context)

#방 리스트 view
@login_required
def room_list(request):
    room_object = Room.objects.all()
    context = {'objects': room_object}
    return render(request, 'chatapp/room_list.html', context=context)

@login_required
def make_room(request):
    if request.method == 'GET':
        context = {}
        return render(request, 'chatapp/make_room.html', context=context)

    elif request.method == 'POST':
        print(request.user)
        if request.method == 'POST':
            room_title = request.POST['room_title']
            room_content = request.POST['room_content']
            room_image = request.FILES['room_image']
            room_date = datetime.today().strftime("%Y/%m/%d %H:%M:%S")  

            Room.objects.create(room_title=room_title, room_content=room_content, room_image=room_image, room_creater=request.user, room_date=room_date)

            context = {'result':'succeed'}
            return render(request, 'chatapp/join.html',context=context)
     
        else:
            context = {}
            return render(request, 'chatapp/make_room.html',context=context)

def detail_room(request, pk):
    room_info = Room.objects.get(id=pk)

    try:
        review_info = Review.objects.filter(review_room=pk).order_by('-review_date')
    except:
        review_info = []

    context = {"room":room_info, "review":review_info}

    return render(request,'chatapp/detail_room.html', context=context)

def make_review(request, pk):
    if request.method == 'POST':
        review_content = request.POST['review_content']
        review_date = datetime.today().strftime("%Y/%m/%d %H:%M:%S")

        Review.objects.create(review_room=pk, review_content=review_content, review_creater=request.user, review_date=review_date)
    
    return redirect(f'/detail_room/{pk}/')
        

YT_PROJECT/chatapp/views/review_views.py
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

from chatapp.models import Room, Review, ReReview
import datetime

@login_required
def make_review(request, pk):
    current = datetime.datetime.utcnow() + datetime.timedelta(hours=9)
    if request.method == 'POST':
        review_content = request.POST['review_content']
        review_date = current.strftime("%Y/%m/%d %H:%M:%S")

        Review.objects.create(review_room=pk, review_content=review_content, review_creater=request.user, review_date=review_date)
    
    return redirect(f'/detail_room/{pk}/')

def delete_review(request, pk, id):
    review_info = Review.objects.filter(review_room=pk, id=id)
    review_info.delete()

    return redirect(f'/detail_room/{pk}/')

def make_re_review(request, pk, id):
    current = datetime.datetime.utcnow() + datetime.timedelta(hours=9)
    if request.method == 'POST':
        review_content = request.POST['rereview_content']
        review_date = current.strftime("%Y/%m/%d %H:%M:%S")

        ReReview.objects.create(review_room=pk, review_id=id, review_content=review_content, review_creater=request.user, review_date=review_date)

    return redirect(f'/detail_room/{pk}/')

def delete_re_review(request, pk, re, id):
    review_info = ReReview.objects.filter(review_room=pk, review_id=re, id=id)
    review_info.delete()

    return redirect(f'/detail_room/{pk}/')

YT_PROJECT/chatapp/views/room_views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from chatapp.forms import UserForm

from django.http import HttpResponse
from chatapp.models import Room, Review, ReReview

import datetime

# Create your views here.

# home view (로그인 상태: room_list.html, 미로그인 상태:login.html)
def chat_home(request):
    if not request.user.is_authenticated:
        return render(request, 'chatapp/login.html',{})
    else:
        return redirect('/room_list/')

#계정 생성 view
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            authenticate(username=username, password=raw_password)  # 사용자 인증
            # login(request, user)  # 로그인
            return render(request,'chatapp/login.html',context={})
    else:
        form = UserForm()
    return render(request, 'chatapp/signup.html', {'form':form})

#방 참가 view
@login_required
def join(request):
    context = {}
    return render(request, 'chatapp/join.html', context=context)

#방 리스트 view
@login_required
def room_list(request):
    room_object = Room.objects.all().order_by('-room_date')
    room_view_best = Room.objects.all().order_by('-room_view')[:5]
    room_like_best = Room.objects.all().order_by('-room_like')[:5]

    context = {'objects': room_object,'views': room_view_best, 'likes':room_like_best}
    return render(request, 'chatapp/room_list.html', context=context)

# 방 생성
@login_required
def make_room(request):
    if request.method == 'GET':
        context = {}
        return render(request, 'chatapp/make_room.html', context=context)

    elif request.method == 'POST':
        current = datetime.datetime.utcnow() + datetime.timedelta(hours=9)
        if request.method == 'POST':
            room_title = request.POST['room_title']
            room_content = request.POST['room_content']
            room_image = []
            for n in [0,1,2]:
                try:
                    room_image.append(request.FILES.getlist('room_image')[n])
                except:
                    room_image.append('')
            room_date = current.strftime("%Y/%m/%d %H:%M:%S")

            Room.objects.create(room_title=room_title, room_content=room_content, 
                                room_image1=room_image[0], room_image2=room_image[1], room_image3=room_image[2], 
                                room_creater=request.user, room_date=room_date)

            context = {'result':'succeed'}
            return redirect('/room_list/')
     
        else:
            context = {}
            return render(request, 'chatapp/make_room.html',context=context)

#방 상세페이지
@login_required
def detail_room(request, pk):
    #room 정보 가져오기
    room_info = Room.objects.get(id=pk)

    #room_view 업데이트 하기
    view_plus = room_info.room_view + 1
    room_info.room_view = view_plus
    room_info.save()

    #이미지 가져오기
    img = [room_info.room_image1, room_info.room_image2, room_info.room_image3]
    img_count = [x for x in img if x!='']

    #리뷰 가져오기
    try:
        review_info = Review.objects.filter(review_room=pk).order_by('-review_date')
    except:
        review_info = ''

    rereview_list = []
    if review_info != '':
        for re in review_info:
            try:
                rereview_list.append(ReReview.objects.filter(review_room=pk, review_id=re.id).order_by('review_date'))
            except:
                rereview_list.append('')
    
    context = {"room":room_info, "img_count":len(img_count) ,"review":review_info, "rereview":rereview_list, "user":str(request.user)}

    return render(request,'chatapp/detail_room.html', context=context)

# 방 삭제
@login_required
def delete_room(request, pk):
    room_info = Room.objects.get(id=pk)
    room_info.delete()

    Review.objects.filter(review_room=pk).delete()

    return redirect('/room_list/')

# 방 수정
@login_required
def modify_room(request, pk):
   
    if request.method == 'GET':
        room_info = Room.objects.get(id=pk)
        context = {'room':room_info}

        print('get방식',room_info)
        return render(request,'chatapp/modify_room.html', context=context)
    
    else:
        room_info = Room.objects.get(id=pk)
        if str(request.user) == str(room_info.room_creater):
            print(room_info.room_creater)
            room_image = []
            for n in [0,1,2]:
                try:
                    room_image.append(request.FILES.getlist('room_image')[n])
                except:
                    room_image.append('')
            
            room_info.room_image1=room_image[0]
            room_info.room_image2=room_image[1]
            room_info.room_image3=room_image[2]
            room_info.room_title = request.POST['room_title']
            room_info.room_content = request.POST['room_content']

            room_info.save()

            return redirect('/detail_room/'+str(pk))
        else:
            return redirect('/detail_room/'+str(pk))

YT_PROJECT/chatapp/templates/chatapp/detail_room.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<br>
<div class="row justify-content-center">
    <h1 style="text-align: center; margin-bottom: 20px;">{{room.room_title}}</h1>

    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <p class="card-text">{{room.room_content|linebreaksbr}}
                </p>
                <hr width ="100%" size = "3">
            </div>
                
                <div id="carouselExampleDark" class="carousel carousel-dark slide" data-interval="false">
                    <!-- <div class="carousel-indicators" id="slideicon">
                        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
                    </div> -->
                    
                    <div class="carousel-inner" id="slideinner">
                        {% if room.room_image1 != '' %}
                        <div class="carousel-item active">
                            <img src="{{room.room_image1.url}}" class="d-block w-20 col-8" alt="..." style="margin:auto;">
                        </div>
                        {% else %}
                        <p style="text-align: center;">No image</p>
                        {% endif %}
                        {% if room.room_image2 != '' %}
                        <div class="carousel-item">
                            <img src="{{room.room_image2.url}}" class="d-block" alt="..." style="margin:auto; width: 25rem">
                        </div>
                        {% endif %}
                        {% if room.room_image3 != '' %}
                        <div class="carousel-item">
                            <img src="{{room.room_image3.url}}" class="d-block w-30" alt="..." style="margin:auto; width: 25rem">
                        </div>
                        {% endif %}
                    </div>
              </div>
        </div>
    </div>
    <br>
    <div style="text-align: center; margin-top: 20px;">
        <a href="/room_list/" class="btn btn-primary ">목록</a>
    </div>
</div>

<!--리뷰-->
<div class="row justify-content-center">
    <div style="height: 50px;"></div>
    <hr width ="100%" size = "3">
    <h3 class="col-8" style="text-align: left; margin-bottom: 20px;"> Review </h3>

    <div class="col-8">
        <button type="button" class="btn btn-light" style="margin:left;" data-bs-toggle="collapse" 
                data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
            <img width="20px" height="20px" src="{% static 'chatapp/img/review_icon.png' %}">
        </button>
    </div>

    <!--input review / collapse-->
    <div class="col-8">
        <div class="collapse" id="collapseWidthExample">
        <form action="/make_review/{{room.id}}/" method="POST">
            {% csrf_token %}
            <textarea class="form-control" placeholder="Write here your Review" name="review_content" height="100%" style="float: left;" required></textarea>
            <button type="submit" style="float: right; color:black; margin: 3px 0 10px 0 ;" class="btn btn-outline-primary btn-sm">Post review</button>
        </form>
        </div>
    </div>

    <!--댓글/대댓글-->
    <div class="col-8">
        {% if review %}
            <!--댓글-->
            {% for n in review %}
                <div class="card" style="border-color: rgb(184, 222, 240); margin-top: 15px; padding: 20px; padding-bottom: 0;">
                    <div style="width:100%; float:left">
                        <p class="card-text col-12" >{{n.review_content|linebreaksbr}}
                            {% if n.review_creater == user %}
                            <a href="/delete_review/{{room.id}}/{{n.id}}" class="btn btn-sm" 
                                    style="color:red; float: right;">X</a>
                            {% endif %}
                        </p>
                        <p class="card-text text-end col-12" style="font-size:10px;">작성자:{{n.review_creater}}
                        <br> {{n.review_date}}</p>
                    </div>

                    <div>
                        <span type="button" style="margin:left; color:blue; font-size: 10px;" data-bs-toggle="collapse"
                            data-bs-target="#collapse{{n.id}}" aria-expanded="false" aria-controls="collapseWidthExample2">
                            답글
                        </span>
                        <div class="collapse col-12" id="collapse{{n.id}}">
                            <form action="/make_re_review/{{room.id}}/{{n.id}}/" method="POST">
                                {% csrf_token %}
                                <input class="form-control  col-12" placeholder="Write here your Review" name="rereview_content" style="float: left;" required>
                                <button type="submit" style="float: right; color:black; margin: 3px 0 10px 0; font-size: .5em;" 
                                    class="btn btn-outline-primary btn-sm">Post</button>
                            </form>
                        </div>
                    </div>
                    <br>
                </div>

                <!--대댓글-->
                {% for v in rereview %}
                    {% for m in v %}
                    {% if m.review_id == n.id %}
                    <div class="row" style="width:100%; margin-top: 3px;">
                        <div class="col-1" style="float:left; text-align: right;">└ &nbsp;</div>
                        <div class="col-10" style="float:right; background: rgb(241, 247, 250);">
                            <p class="card-text text-start col-10" style="font-size:15px; float: left; word-break:break-all;">
                                {{m.review_content|linebreaksbr}}
                            </p>
                            {% if m.review_creater == user %}
                            <a href="/delete_re_review/{{room.id}}/{{n.id}}/{{m.id}}/" class="btn btn-sm text-end"  
                                    style="color:red; font-size:10px; float: right;"> X </a>
                            {% endif %}
                            <span class="card-text text-end" style="font-size:10px; float: right;">작성자:{{m.review_creater}} <br> {{m.review_date}}</span><br>
                            <!--대댓글 삭제-->
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                {% endfor %}
            {% endfor %}        
        {% else %}
        <hr width ="100%" size = "3">
        <div height="150px">
            <p style="text-align: center;">Have no review</p>
        </div>
        {% endif %}
        <br> 
    </div>
    <hr width ="100%" size = "3">
    <!--댓글/대댓글 끝-->

</div>

{% if room.room_creater == user %}
<div class="row justify-content-center">
    <a href="/modify_room/{{room.id}}/" style="color:white; margin: 3px 0 10px 0;" class="btn btn-primary col-6">Modify</a>
</div>
<div class="row justify-content-center">
    <a href="/delete_room/{{room.id}}/" style="color:white; margin: 3px 0 10px 0;" class="btn btn-danger col-6">Delete</a>
</div>

{% endif %}
</body>
</html>

<script>
    var img_count = "{{img_count}}";
    
    $(document).ready(function() {
        console.log($('.card-text').text())
        if(img_count > 1) {
            $('#slideicon').append('<button type="button" data-bs-target="#carouselExampleDark" '+
                        'data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>'+
                        '<button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>')
            $('#slideinner').append('<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">' +
                    '<span class="carousel-control-prev-icon" aria-hidden="true"></span>'+
                    '<span class="visually-hidden">Previous</span></button>'+
                    '<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">'+
                    '<span class="carousel-control-next-icon" aria-hidden="true"></span>'+
                    '<span class="visually-hidden">Next</span></button>')
            
            if(img_count > 2) {
                $('#slideicon').append('<button type="button" data-bs-target="#carouselExampleDark" '+
                                    'data-bs-slide-to="2" aria-label="Slide 3"></button>')
            }
        }
    })
</script>

{% endblock %}

YT_PROJECT/chatapp/templates/chatapp/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="row alert alert-danger col-4">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

YT_PROJECT/chatapp/templates/chatapp/join.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    </br></br>
    <div class="row justify-content-center" style="text-align: center; margin: 30px 0px 40px 0px;">
        <h2>Make Room or Join</h2>
    </div>

    <div class="row justify-content-center">
        <a href="/make_room/" class="card text-bg-dark align-items-center col-5" id="imgdiv1" style="margin:10px;">
            <img src="{% static 'chatapp/imgs/makeroom.png' %}" class="card-img" id="img1" style="width:100%; height:100%;">
            <div class="card-img-overlay" id="imgcontent1">
                <h5 class="card-title">Make Room</h5>
                <p class="card-text"><small>Do you have interesting story?</small></p>
                <h6 class="card-text">You can share story.</h6>
            </div>
        </a>

        <a href="/room_list/" class="card text-bg-dark align-items-center col-5" id="imgdiv2" style="margin:10px;">
            <img src="{% static 'chatapp/imgs/joinroom.png' %}" class="card-img" id="img2" style="width:100%; height:100%;">
            <div class="card-img-overlay" id="imgcontent2">
                <h5 class="card-title">Join Room</h5>
                <p class="card-text">Are you ready?</p>
                <p class="card-text"><small>Let's go!</small></p>
            </div>
        </a>
    </div>
</body>
    
<script>
    $(document).ready(function(){
        result = {result}
        alert(result)
    })

    $('#imgdiv1').mouseover(function(){
        $('#img1').css('opacity',0.1);
    })

    $('#imgdiv1').mouseleave(function(){
        $('#img1').css('opacity',1);
    })

    $('#imgdiv2').mouseover(function(){
        $('#img2').css('opacity',0.1);
    })

    $('#imgdiv2').mouseleave(function(){
        $('#img2').css('opacity',1);
    })


</script>
</html>
{% endblock %}

YT_PROJECT/chatapp/templates/chatapp/login.html
{% extends "base.html" %}

{% block content %}
    </br></br>
    <div class="row justify-content-center" style="text-align: center; margin: 30px 0px 40px 0px;">
        <h2>Make your account and SHOW YOUR LOGIC!!!</h2>
    </div>
    <form class="row justify-content-center" name="account" action="{% url 'chatapp:login' %}" method="POST">
    {% csrf_token %}
    <div class="col-6">
        <div class="input-group input-group-sm mb-2">
            <label for="username" class="input-group-text" id="inputGroup-sizing">&nbsp&nbsp&nbsp ID &nbsp&nbsp&nbsp&nbsp</label>
            <input type="text" name="username" id="username" class="form-control" required>
        </div>
        
        <div class="input-group input-group-sm">
            <label for="password" class="input-group-text" id="inputGroup-sizing">Password</label>
            <input type="password" name="password" id="password" class="form-control" required>
        </div>
        <br>
        <p class="row justify-content-center">
            <button type="submit" class="btn btn-secondary col-3" style="font-size: 12px;">GO!</button>
        </p>
    </div>
    </form>
   
    <p class="row justify-content-center">
        <a href="/signup/" class="col-5" style="text-align: center; text-decoration: none; font-size: 10px;">계정만들기</a>
    </p>

    
</body>
</html>
{% endblock %}

YT_PROJECT/chatapp/templates/chatapp/signup.html
{% extends "base.html" %}

{% block content %}
    </br></br>
    <div class="row justify-content-center" style="text-align: center; margin: 30px 0px 40px 0px;">
        <h2>Make your account and SHOW YOUR LOGIC!!!</h2>
    </div>

    <div class="row justify-content-center">
        {% include "chatapp/form_errors.html" %}
    </div>

    <form class="row justify-content-center" action="{% url 'chatapp:signup' %}" method="POST">
    {% csrf_token %}
        </br>
        <div class="col-4">
            <div class="input-group input-group-sm mb-3">
                <label for="username" class="input-group-text" id="inputGroup-sizing-md">&nbsp&nbsp&nbsp ID &nbsp&nbsp&nbsp&nbsp</label>
                <input type="text" name='username' id="username" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-md" required>
            </div>

            <div class="input-group input-group-sm mb-3" id="pwdiv1">
                <label for="password1" class="input-group-text" id="inputGroup-sizing-md">Password</label>
                <input type="password" id="password1" name='password1' class="form-control" required>
                <span id="pwstate1" style="width:100%; color:gray; font-size:10px;">최소 8 자, 하나 이상의 문자와 하나의 숫자를 입력해주세요.</span>
            </div>
            
            <div class="input-group input-group-sm mb-3" id="pwdiv2">
                <label for="password2" class="input-group-text" id="inputGroup-sizing-md">Password </br> Check</label>
                <input type="password" id="password2" name='password2' class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-md" required>
                <span id="pwstate2" style="width:100%; color:gray; font-size:10px;">위와 동일한 패스워드를 입력해주세요.</span>
            </div>

            <div class="input-group input-group-sm mb-3">
                <label for="email" class="input-group-text" id="inputGroup-sizing-md">&nbsp E-mail &nbsp</label>
                <input type="email" id="email" name='email' class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-md" required>
            </div>

            <p class="row justify-content-center">
                <button type="submit" class="btn btn-secondary col-4">Make Account!</button>
            </p>
        </div>
    </form>
    <p class="row justify-content-center">
        <a href="/" class="col-2" style="text-align: center; text-decoration: none; font-size: 10px;">로그인하기</a>
    </p>
    
</body>
</html>

<script>
    $('#password1').focusout(function(){
        var reg = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;
        $('#pwstate1').remove()
        txt = $('#password1').val();
        if( !reg.test(txt) ) {
            $('#password1').val('');
            $('#password2').val('');
            $('#pwdiv1').append('<span id="pwstate1" style="width:100%; color:red; font-size:10px;">'+
                                '다시 입력해주세요.(최소 8자, 하나 이상의 문자와 하나의 숫자)</span>')
            return 0;
        }
        else {
            $('#pwdiv1').append('<span id="pwstate1" style="width:100%; color:blue; font-size:10px;">'+
                                '적합한 패스워드 입니다..</span>')
            return 0;
        }
    });

    $('#password2').focusout(function(){
        pw1 = $('#password1').val()
        pw2 = $('#password2').val()
        $('#pwstate2').remove()
        if(pw1 != pw2){
            $('#password2').val('');
            $('#pwdiv2').append('<span id="pwstate2" style="width:100%; color:red; font-size:10px;">'+
                            '위의 패스워드와 다릅니다.</span>')
            return 0;
        }
        else {
            $('#pwdiv2').append('<span id="pwstate2" style="width:100%; color:blue; font-size:10px;">'+
                                '위와 동일합니다.</span>')
            return 0;
        }
    });

</script>
{% endblock %}